# Generated by Django 5.0.7 on 2024-11-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_sport_team_venue_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='sport',
            new_name='_fkey_sport',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='teams',
            new_name='_fkey_teams',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='venue',
            new_name='_fkey_venue',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='sport',
            new_name='_fkey_sport',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='country',
            new_name='_fkey_country',
        ),
    ]
