# Generated by Django 5.0.7 on 2024-11-21 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='_fkey_teams',
        ),
        migrations.AddField(
            model_name='event',
            name='_fkey_away_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='away_events', to='events.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='_fkey_home_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='home_events', to='events.team'),
            preserve_default=False,
        ),
    ]
