#!/bin/bash

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES_ACCESS_USER WITH ENCRYPTED PASSWORD '$POSTGRES_ACCESS_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_ACCESS_USER;
    GRANT USAGE, CREATE ON SCHEMA public TO $POSTGRES_ACCESS_USER;
EOSQL